/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "services_constants.h"



const servicesConstants g_services_constants;

servicesConstants::servicesConstants() {
}



