/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef services_CONSTANTS_H
#define services_CONSTANTS_H

#include "services_types.h"



class servicesConstants {
 public:
  servicesConstants();

};

extern const servicesConstants g_services_constants;



#endif
