// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "defs.h"
#include "SimpleDB.h"
#include "file_system/file_system.hpp"
#include "http/http.hpp"

#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>

#include <vector>
#include <fstream>
#include <thread>
#include <chrono>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class SimpleDBHandler : virtual public SimpleDBIf {
private:
  std::vector<int> ports;
  int myPort;

 public:
  SimpleDBHandler(int port) {
    this->myPort = port;

    // appending my port to the ports file
    std::ofstream portsFileOutput;
    portsFileOutput.open(CONTROL_FILENAME, std::ios::app);
    portsFileOutput << port << "\n";
    portsFileOutput.close();

    std::ifstream portsFileInput(CONTROL_FILENAME);
    std::string line;
    if(portsFileInput.is_open())
      {
	while(getline(portsFileInput, line))
	  {
	    ports.push_back(atoi(line.c_str()));
	  }
      }
    portsFileInput.close();

    if(this->ports.size() > 1)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "There are other servers running!" << std::endl;
	std::cout << "I Should tell them about me! :D" << std::endl;
	for(int i = 0; i < this->ports.size() - 1 ; i++) // the last port is me!
	  {
	    shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[i]));
	    shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	    shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	    SimpleDBClient client(protocol);
	    transport->open();
	    client.update_server();
	    transport->close();
	  }
	std::cout << "Done! :D" << std::endl;

	// avisar aos outros servidores que mais um foi conectado
	// pra isso tem que criar mais um servico no thrift de atualizar de acordo
	// com o arquivo de controle
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "I'm alone :(" << std::endl;
      }

    #if DEBUG
    std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
    std::cout << "Server Created!" << std::endl;
    std::cout << "My Port: " << port << std::endl;
    std::cout << "Ports that I know: " << std::endl;
    for(int i = 0; i < this->ports.size(); i++)
      {
	std::cout << "Port " << i+1 << ": " << this->ports[i] << std::endl;
      }
    #endif
  }

  int apply_hash(const char * s, int size, int count)
  {
    int hash = 0;
    for(int i = 0; i < size; i++)
      {
	hash += (int)s[i];
      }

#if DEBUG
    std::cout << "Applying Hash" << std::endl;
    std::cout << "Value before Hash: " << hash << std::endl;
#endif

    hash = hash % count;

#if DEBUG
    std::cout << "Value after hash: " << hash << std::endl;
#endif

    return hash;
  }

  void get(File& _return, const std::string& url) {
#if DEBUG
    std::cout << "url: " << url << std::endl;
    std::vector<std::string> tokens = Tokenizer::split(url.c_str(), '/');

    for(int i = 0; i < tokens.size(); i++)
      {
	std::cout << "token " << i << ": " << tokens[i] << std::endl;
      }
#endif
    
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());

    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "It's my work!" << std::endl;

	Node * result = FileSystem::instance()->search(url);

	if(result != NULL)
	  {
	    _return.creation = result->get_creation();
	    _return.modification = result->get_modification();
	    _return.version = result->get_version();
	    _return.name = result->get_name();
	    _return.content = result->get_data();
	  }
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	client.get(_return, url);
	transport->close();
      }

    std::cout << "returning: " << _return << std::endl;
    printf("get\n");
  }

  void get_list(std::vector<File> & _return, const std::string& url) {
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());

    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "It's my work!" << std::endl;
	Node * result = FileSystem::instance()->search(url);
	Node * aux;
	std::vector<File*> files;
	for(int i = 0; i < result->get_child_count(); i++)
	  {
	    aux = result->get_child(i);
	    files.push_back(new File());
	    files[i]->creation = aux->get_creation();
	    files[i]->modification = aux->get_modification();
	    files[i]->version = aux->get_version();
	    files[i]->name = aux->get_name();
	    files[i]->content = aux->get_data();

	    _return.push_back(*(files[i]));
	  }
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	client.get_list(_return, url);
	transport->close();
      }

    printf("get_list\n");
  }

  version_t add(const std::string& url, const std::string& content) {

    std::vector<std::string> tokens = Tokenizer::split(url.c_str(), '/');
    if(tokens.size() > 2)
      {
	File f;
	std::string url2 = "";
	for(int i = 1; i < tokens.size() - 1; i++)
	  {
	    url2 += "/" + tokens[i];
	    std::cout << url2 << std::endl;
	    this->get(f, url2);
	    if(f.name.size() > 0)
	      {
		std::cout << "nao nulo" << std::endl;
	      }
	    else
	      {
		this->add(url2, "");
	      }
	    
	    std::cout << "file: " << f << std::endl;
	  }
      }
    
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());

    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "It's my work!" << std::endl;
	std::cout << "url:" << url << std::endl;
	Node * result = FileSystem::instance()->insert(url, content);
	printf("add\n");
	return result->get_version();
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	int v;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	v = client.add(url, content);
	transport->close();

	return v;
      }

    printf("add\n");
  }

  version_t update(const std::string& url, const std::string& content) {
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());

    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "Its my work! :D" << std::endl;
	Node * result = FileSystem::instance()->edit(url, content);
	printf("update\n");
	return result->get_version();
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	int v;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	v = client.update(url, content);
	transport->close();
	return v;
      }

    printf("get_list\n");
  }

  void delete_file(File& _return, const std::string& url) {
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());

    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "Its my work! :D" << std::endl;
	Node * result = FileSystem::instance()->remove(url);

	_return.creation = result->get_creation();
	_return.modification = result->get_modification();
	_return.version = result->get_version();
	_return.name = result->get_name();
	_return.content = result->get_data();
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	client.delete_file(_return, url);
	transport->close();
      }
    printf("delete_file\n");
  }

  version_t update_with_version(const std::string& url, const std::string& content, const version_t version) {
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());


    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "Its my work! :D" << std::endl;
	Node * s = FileSystem::instance()->search(url);

	if(s->get_version() == version)
	  {
	    Node * result = FileSystem::instance()->edit(url, content);
	    return result->get_version();
	  }
	else
	  {
	    return -1;
	  }
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	int v;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	v = client.update_with_version(url, content, version);
	transport->close();

	return v;
      }

    printf("update_with_version\n");
  }

  void delete_with_version(File& _return, const std::string& url, const version_t version) {
    std::cout << "=========================================" << std::endl;
    int hash = apply_hash(url.c_str(), url.size(), this->ports.size());

    if(this->ports[hash] == this->myPort)
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "Its my work! :D" << std::endl;
	Node * s = FileSystem::instance()->search(url);

	if(s->get_version() == version)
	  {
	    Node * result = FileSystem::instance()->remove(url);

	    _return.creation = result->get_creation();
	    _return.modification = result->get_modification();
	    _return.version = result->get_version();
	    _return.name = result->get_name();
	    _return.content = result->get_data();
	  }
      }
    else
      {
	std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
	std::cout << "This is not my work!" << std::endl;
	std::cout << "This is " << this->ports[hash] << " job!" << std::endl;
	shared_ptr<TTransport> socket(new TSocket("localhost", this->ports[hash]));
	shared_ptr<TTransport> transport(new TBufferedTransport(socket));
	shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	SimpleDBClient client(protocol);
	transport->open();
	client.delete_with_version(_return, url, version);
	transport->close();
      }
    printf("delete_with_version\n");
  }

    void update_server() {
      std::cout << "=========================================" << std::endl;
      std::cout << "MSG FROM SERVER " << this->myPort << std::endl;
      std::cout << "A new friend joined the server!" << std::endl;
      std::cout << "Let's see who it is!" << std::endl;

      this->ports.clear();
      std::ifstream portsFileInput(CONTROL_FILENAME);
      std::string line;
      if(portsFileInput.is_open())
	{
	  while(getline(portsFileInput, line))
	    {
	      ports.push_back(atoi(line.c_str()));
	    }
	}
      portsFileInput.close();

      std::cout << "Ports that I know: " << std::endl;
      for(int i = 0; i < this->ports.size(); i++)
	{
	  std::cout << "Port " << i+1 << ": " << this->ports[i] << std::endl;
	}
      std::cout << "=========================================" << std::endl;
  }

};

void initialize_server(int port)
{
  shared_ptr<SimpleDBHandler> handler(new SimpleDBHandler(port));
  shared_ptr<TProcessor> processor(new SimpleDBProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);

  server.serve();
}

int main(int argc, char **argv) {

  initialize_server(atoi(argv[1]));
  /*
  int thread_count = argc - 1;
  std::thread * db_servers = new std::thread[thread_count];

  int i;
  for(i = 0; i < (thread_count - 1); i++)
    {
      db_servers[i] = std::thread(&initialize_server, atoi(argv[i+1]));
      db_servers[i].detach();

      std::this_thread::sleep_for(std::chrono::seconds(1));
      std::cout << "==================" << std::endl;
    }
  initialize_server(atoi(argv[i+1]));
  */

  return 0;
}
